#!/usr/bin/env python3
"""
autograph moc — generate Maps of Content from vault cards.
All domain/type/status logic from schema.json. No hardcoded values.

Commands:
  moc.py generate <vault-dir> [schema.json]
  moc.py generate <vault-dir> [schema.json] --domain <name>
"""

import re
import sys
import json
from pathlib import Path
from collections import defaultdict
from datetime import datetime

from common import (
    load_schema, parse_frontmatter, walk_vault, rel_path,
    infer_domain, get_node_types, get_status_order, write_card
)


# Домен приходит из фронтматтера карточки, и enforce.py его не проверяет — он лишь
# подставляет отсутствующий. Значит `domain: work/clients` встречается на самом деле, а в
# имени файла давал MOC/MOC-work/clients.md: каталога work/ нет, запись падала, и один
# кривой домен ронял генерацию ВСЕХ MOC. Домен при этом не теряется: в заголовке и в
# тексте остаётся как написан, безопасная форма нужна только имени файла и ссылке на него.
_UNSAFE_IN_NAME = re.compile(r'[^\w.\-]+', re.UNICODE)


def moc_stem(domain: str) -> str:
    """MOC file name for a domain, without extension."""
    safe = _UNSAFE_IN_NAME.sub('-', str(domain)).strip(' .-')
    return f'MOC-{safe}' if safe else 'MOC-other'


def build_moc_data(vault_dir: Path, schema: dict, domain_filter: str = None) -> dict:
    """Scan vault, group cards by domain → type → industry/category → status."""
    files = walk_vault(vault_dir)
    domains = defaultdict(list)

    for md in files:
        rp = rel_path(md, vault_dir)
        try:
            content = md.read_text(errors='replace')
        except Exception:
            continue

        fm, body, _ = parse_frontmatter(content)
        if fm is None:
            continue

        domain = fm.get('domain') or infer_domain(rp, schema)
        if domain_filter and domain != domain_filter:
            continue

        card_type = fm.get('type', 'note')
        status = fm.get('status', '')
        name = fm.get('title') or md.stem.replace('-', ' ').title()
        rp_noext = rp.replace('.md', '')

        card = {
            'path': rp_noext,
            'name': name,
            'type': card_type,
            'status': status,
            'priority': fm.get('priority', ''),
            'industry': fm.get('industry', 'Other'),
            'region': fm.get('region', ''),
            'deal_status': fm.get('deal_status', ''),
            'deal_deadline': fm.get('deal_deadline', ''),
            'responsible': fm.get('responsible', ''),
            'potential': fm.get('potential', ''),
            'source': fm.get('source', ''),
            'description': fm.get('description', ''),
        }
        domains[domain].append(card)

    return dict(domains)


def format_card_line(card: dict) -> str:
    """Format a single MOC line with context."""
    path = card['path']
    name = card['name']
    parts = []

    if card['status']:
        parts.append(card['status'])
    if card['priority']:
        parts.append(f"p:{card['priority']}")
    if card['deal_status']:
        parts.append(card['deal_status'])
    if card['deal_deadline']:
        parts.append(f"⏰ {card['deal_deadline']}")
    if card['region']:
        parts.append(card['region'].upper())
    if card['responsible']:
        parts.append(f"→ {card['responsible']}")
    if card['potential']:
        parts.append(f"🔥{card['potential']}")

    context = ', '.join(parts)
    return f"- [[{path}|{name}]]{' — ' + context if context else ''}"


def generate_moc(domain: str, cards: list, schema: dict) -> str:
    """Generate MOC markdown for a domain."""
    status_order = get_status_order(schema)
    lines = [
        f"---",
        f'description: "MOC — {domain.title()} domain index ({len(cards)} cards)"',
        f"type: moc",
        f"---",
        f"",
        f"# MOC — {domain.title()}",
        f"",
        f"_Auto-generated by autograph. {datetime.now().strftime('%Y-%m-%d %H:%M')}_",
        f"_Cards: {len(cards)}_",
        f"",
    ]

    # Group by type
    by_type = defaultdict(list)
    for c in cards:
        by_type[c['type']].append(c)

    for card_type in sorted(by_type.keys()):
        type_cards = by_type[card_type]
        lines.append(f"## {card_type.title()} ({len(type_cards)})")
        lines.append("")

        # Sub-group by industry
        by_industry = defaultdict(list)
        for c in type_cards:
            by_industry[c['industry']].append(c)

        for industry in sorted(by_industry.keys()):
            ind_cards = by_industry[industry]
            if len(by_industry) > 1:
                lines.append(f"### {industry}")
                lines.append("")

            # Sort by status priority
            ind_cards.sort(key=lambda c: status_order.get(c['status'], 99))

            for c in ind_cards:
                lines.append(format_card_line(c))

            lines.append("")

    # Stats
    type_counts = defaultdict(int)
    status_counts = defaultdict(int)
    for c in cards:
        type_counts[c['type']] += 1
        if c['status']:
            status_counts[c['status']] += 1

    lines.append("## Stats")
    lines.append("")
    lines.append("| Type | Count |")
    lines.append("|------|-------|")
    for t, count in sorted(type_counts.items(), key=lambda x: -x[1]):
        lines.append(f"| {t} | {count} |")
    lines.append("")
    lines.append("| Status | Count |")
    lines.append("|--------|-------|")
    for s, count in sorted(status_counts.items(), key=lambda x: -x[1]):
        lines.append(f"| {s} | {count} |")

    return '\n'.join(lines)


def generate_hub(data: dict) -> str:
    """Единый хаб vault/MOC.md: ссылки на фактически сгенерированные доменные MOC.

    Пересобирается при каждом generate, чтобы первый шаг цепочки
    CORE → MOC.md → MOC/MOC-{domain} → карточка не протухал при
    добавлении/удалении домена (issue #113).
    """
    lines = [
        '# MOC — индекс тем',
        '',
        'Хабы графа: темы → карточки. На вопрос «что я знаю про X» начни отсюда и иди по ссылкам.',
        'Регенерится ночью (autograph `moc.py generate`) — может слегка отставать; если пусто, ищи через `grep`.',
        '',
    ]
    for domain in sorted(data):
        cards = data[domain]
        if not cards:
            continue
        lines.append(f'- [[MOC/{moc_stem(domain)}]] — карточек: {len(cards)}')
    lines.append('')
    return '\n'.join(lines)


def main():
    args = sys.argv[1:]
    if not args or args[0] in ('-h', '--help'):
        print(__doc__)
        sys.exit(0)

    cmd = args[0]
    vault_dir = Path(args[1]) if len(args) > 1 else None

    if not vault_dir or not vault_dir.is_dir():
        print("Error: vault directory required", file=sys.stderr)
        sys.exit(1)

    schema_path = None
    for a in args:
        if a.endswith('.json') and Path(a).exists():
            schema_path = Path(a)
            break
    schema = load_schema(schema_path)

    domain_filter = None
    if '--domain' in args:
        idx = args.index('--domain')
        if idx + 1 < len(args):
            domain_filter = args[idx + 1]

    if cmd == 'generate':
        data = build_moc_data(vault_dir, schema, domain_filter)

        moc_dir = vault_dir / 'MOC'
        moc_dir.mkdir(exist_ok=True)
        total_links = 0
        # MOC пишем тем же атомарным швом, что и карточки: обрыв посреди записи оставил
        # бы обрезанный MOC.md, а ночной brain делает `git add -A` — огрызок уехал бы
        # в историю vault как «текущий индекс тем памяти».

        if domain_filter:
            cards = data.get(domain_filter, [])
            moc_text = generate_moc(domain_filter, cards, schema)
            outpath = moc_dir / f'{moc_stem(domain_filter)}.md'
            write_card(outpath, moc_text)
            link_count = moc_text.count('[[')
            total_links += link_count
            print(f"✓ Generated: {outpath.relative_to(vault_dir)}")
            print(f"  {link_count} wikilinks")
        else:
            for domain, cards in sorted(data.items()):
                if not cards:
                    continue
                moc_text = generate_moc(domain, cards, schema)
                stem = moc_stem(domain)
                if stem != f'MOC-{domain}':
                    print(f"  domain {domain!r} → {stem}.md (unsafe in a file name)")
                outpath = moc_dir / f'{stem}.md'
                write_card(outpath, moc_text)
                link_count = moc_text.count('[[')
                total_links += link_count
                print(f"✓ Generated: {outpath.relative_to(vault_dir)}")
                print(f"  {link_count} wikilinks")

        # Хаб собирается из ПОЛНОГО скана: прогон с --domain обновляет один доменный
        # файл, но индекс всё равно должен перечислять все домены vault'а.
        # Ссылки — только на реально существующие MOC-файлы: домен, чей файл ещё
        # не сгенерирован, попадёт в хаб при первом же полном прогоне (ночь).
        hub_data = build_moc_data(vault_dir, schema, None) if domain_filter else data
        hub_data = {
            d: cards for d, cards in hub_data.items()
            if cards and (moc_dir / f'{moc_stem(d)}.md').exists()
        }
        if any(hub_data.values()):
            hub_text = generate_hub(hub_data)
            write_card(vault_dir / 'MOC.md', hub_text)
            total_links += hub_text.count('[[')
            print("✓ Generated: MOC.md")

        print(f"\nTotal: {total_links} wikilinks across {len(data)} domains")
    else:
        print(f"Unknown command: {cmd}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
